name: Deploy Static Site

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 134.109.192.158
          username: dmadmin
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*"
          target: "/mnt/extern/webapps/sodrepo"
